// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TabSaver
{
    internal sealed partial class Vsix
    {
        public const string Id = "TabSaver.1bc241ff-6f67-4806-aec0-a06644553ae7";
        public const string Name = "TabSaver";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "hristofor.yordanov.92";
        public const string Tags = "";
    }
}
