// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TabSaver
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string TabSaverPackageString = "fe04de0a-2316-4e08-ab8b-7b1feaf83168";
        public static Guid TabSaverPackage = new Guid(TabSaverPackageString);

        public const string TabSaverCommandSetString = "31a662c6-2290-450a-846e-3b85c6fe17a2";
        public static Guid TabSaverCommandSet = new Guid(TabSaverCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TabSaverMenu = 0x1000;
        public const int MainMenuTabSaverGroup = 0x0100;
        public const int TabSaverCommandsGroup = 0x0200;
        public const int SavePinnedTabsCommand = 0x0010;
        public const int SaveAllTabsCommand = 0x0020;
        public const int RestoreSavedTabsCommand = 0x0030;
        public const int TestButton = 0x0040;
    }
}